name: Golden Pipeline - CI/CD

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_TOKEN:
        required: true
      GH_ACCESS_TOKEN:
        required: true

jobs:
  checkout-and-test:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.get_version.outputs.IMAGE_TAG }}  # Exporta a tag da imagem
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Salvar arquivos como artefato
        uses: actions/upload-artifact@v4
        with:
          name: flask-files
          path: ./
      - name: Obter e Criar tag da imagem docker
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          SHORT_SHA=$(git rev-parse --short HEAD)
          IMAGE_TAG="$VERSION-$SHORT_SHA"
  
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
  
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
  
          echo "Versão extraída: $VERSION"
          echo "SHA do commit: $SHORT_SHA"
          echo "Tag da imagem gerada: $IMAGE_TAG"

  build-and-push-image-frontend:
    needs: checkout-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Verificar se o repositório já existe no Docker Hub
        id: check_repo
        run: |
          REPO_NAME=${{ secrets.DOCKER_USERNAME }}/react
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/react/")
          if [ "$STATUS" == "404" ]; then
            echo "Repositório não encontrado. Criando..."
            curl -X POST -H "Content-Type: application/json" \
              -H "Authorization: Bearer ${{ secrets.DOCKER_TOKEN }}" \
              -d '{"name": "react", "is_private": false}' \
              https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/
          else
            echo "Repositório já existe."
          fi

      - name: Recuperar tag da imagem
        run: echo "IMAGE_TAG=${{ needs.checkout-and-test.outputs.image_tag }}" >> $GITHUB_ENV

      - name: Construir e taguear a imagem
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/react:$IMAGE_TAG ./frontend
          docker tag ${{ secrets.DOCKER_USERNAME }}/react:$IMAGE_TAG ${{ secrets.DOCKER_USERNAME }}/react:latest

      - name: Enviar imagem para o repositório
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/react:$IMAGE_TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/react:latest
        

  build-and-push-image-backend:
    needs: checkout-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Verificar se o repositório já existe no Docker Hub
        id: check_repo
        run: |
          REPO_NAME=${{ secrets.DOCKER_USERNAME }}/flask
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/flask/")
          if [ "$STATUS" == "404" ]; then
            echo "Repositório não encontrado. Criando..."
            curl -X POST -H "Content-Type: application/json" \
              -H "Authorization: Bearer ${{ secrets.DOCKER_TOKEN }}" \
              -d '{"name": "flask", "is_private": false}' \
              https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/
          else
            echo "Repositório já existe."
          fi

      - name: Recuperar tag da imagem
        run: echo "IMAGE_TAG=${{ needs.checkout-and-test.outputs.image_tag }}" >> $GITHUB_ENV
  
      - name: Construir e taguear a imagem
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask:$IMAGE_TAG ./backend
          docker tag ${{ secrets.DOCKER_USERNAME }}/flask:$IMAGE_TAG ${{ secrets.DOCKER_USERNAME }}/flask:latest

      - name: Enviar imagem para o repositório
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/flask:$IMAGE_TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/flask:latest

  deploy-argocd:
    needs: 
      - checkout-and-test
      - build-and-push-image-backend
      - build-and-push-image-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório dos manifestos do Kubernetes
        uses: actions/checkout@v4
        with:
          repository: golden-pipeline/to-do-list-k8s
          ref: feature-manifestos
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Recuperar tag da imagem
        run: echo "IMAGE_TAG=${{ needs.checkout-and-test.outputs.image_tag }}" >> $GITHUB_ENV

      - name: Atualizar imagem do Frontend
        run: |
          echo "Tag da imagem: $IMAGE_TAG"
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/react:$IMAGE_TAG|" k8s/frontend/deployment.yaml
          cat k8s/frontend/deployment.yaml
        
      - name: Atualizar imagem do Backend
        run: |
          echo "Tag da imagem: ${{ needs.checkout-and-test.outputs.image_tag }}"
          IMAGE_TAG="${{ needs.checkout-and-test.outputs.image_tag }}"
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/flask:$IMAGE_TAG|" k8s/backend/deployment.yaml
          cat k8s/backend/deployment.yaml

      - name: Commit e push das alterações
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add k8s/frontend/deployment.yaml
          git add k8s/backend/deployment.yaml
          git commit -m "Atualizando imagens da aplicação:${{ needs.checkout-and-test.outputs.image_tag }}"
          git push origin feature-manifestos